services:
  - type: web
    name: quest-platform
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: TEXTQUEST_UPLOADS_DIR
        value: /var/data/uploads
      - key: JAVA_TOOL_OPTIONS
        value: >-
          -XX:MaxRAMPercentage=75.0
          -Dhibernate.connection.driver_class=org.postgresql.Driver
          -Dhibernate.connection.url=jdbc:postgresql://dpg-d47nl4ripnbc73d147cg-a.oregon-postgres.render.com:5432/questdb_3g3w?sslmode=require
          -Dhibernate.connection.username=questdb_3g3w_user
          -Dhibernate.connection.password=e5siiQ5YYVD7D7ULGvWvsGSgUEywAUU2
          -Dhibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider
          -Dhibernate.hikari.maximumPoolSize=10
          -Dhibernate.hikari.minimumIdle=1
          -Dhibernate.hikari.idleTimeout=300000
          -Dhibernate.hikari.maxLifetime=1800000
          -Dhibernate.hikari.connectionTimeout=10000
          -Dhibernate.hikari.validationTimeout=5000
      - key: LIQUIBASE_URL
        value: jdbc:postgresql://dpg-d47nl4ripnbc73d147cg-a.oregon-postgres.render.com:5432/questdb_3g3w?sslmode=require
      - key: LIQUIBASE_USERNAME
        value: questdb_3g3w_user
      - key: LIQUIBASE_PASSWORD
        value: e5siiQ5YYVD7D7ULGvWvsGSgUEywAUU2