services:
  - type: web
    name: quest-platform
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=75.0 -Duploads.dir=/tmp/uploads"
    healthCheckPath: /
    ports:
      - port: 8080
        protocol: http