package com.javarush.apalinskiy.repository.quest;

import com.javarush.apalinskiy.domain.quest.custom.CustomQuest;
import com.javarush.apalinskiy.domain.quest.QuestNode;
import lombok.Getter;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Contract for storing, querying, and moderating custom quests.
 * <p>
 * Unless stated otherwise, methods are expected to be idempotent with respect to
 * missing entities (i.e., no-op + {@code false} / exception where applicable).
 * Implementations SHOULD return quests ordered by {@code updatedAt} descending
 * for {@link #listAll()} and {@link #listByOwner(String)} to provide a stable UX.
 * </p>
 */
public interface CustomQuestRepository {

    /**
     * Persists a new quest with a generated identifier.
     *
     * @param ownerId     owner user id
     * @param name        quest name
     * @param startId     start node id
     * @param nodes       quest nodes (stored by value/copy)
     * @param published   initial published flag
     * @param versionNote optional version/comment label
     */
    void create(String ownerId, String name, int startId, List<QuestNode> nodes,
                boolean published, String versionNote);

    /**
     * Retrieves a quest by id.
     *
     * @param id quest id
     * @return optional quest; empty if not found
     */
    Optional<CustomQuest> get(String id);

    /**
     * Lists all quests ordered by {@code updatedAt} descending.
     *
     * @return immutable list of quests
     */
    List<CustomQuest> listAll();

    /**
     * Lists quests for the given owner ordered by {@code updatedAt} descending.
     *
     * @param ownerId owner user id
     * @return immutable list of quests
     */
    List<CustomQuest> listByOwner(String ownerId);

    /**
     * Replaces graph, start node, publish flag and version note of an existing quest.
     * Implementations SHOULD update {@code updatedAt}.
     *
     * @param id          quest id
     * @param startId     new start node id
     * @param nodes       replacement nodes
     * @param published   new published flag
     * @param versionNote new version/comment label
     */
    void update(String id, int startId, List<QuestNode> nodes,
                boolean published, String versionNote);

    /**
     * Deletes a quest by id.
     *
     * @param id quest id
     * @return {@code true} if a quest was removed, {@code false} otherwise
     */
    boolean delete(String id);

    /**
     * Deletes a quest only if the provided owner id matches the quest owner.
     *
     * @param id      quest id
     * @param ownerId expected owner id
     * @return {@code true} if removed; {@code false} if not found or owner mismatch
     */
    boolean deleteIfOwner(String id, String ownerId);

    /**
     * Pending "new quest" submission for moderation.
     */
    @Getter
    final class PendingNew {
        private final String pendingId;
        private final String ownerId;
        private final String name;
        private final int startId;
        private final List<QuestNode> nodes;
        private final String versionNote;
        private final Instant submittedAt;

        /**
         * @param pendingId   moderation id generated by repository
         * @param ownerId     owner user id
         * @param name        quest name
         * @param startId     start node id
         * @param nodes       submitted nodes
         * @param versionNote version/comment label
         * @param submittedAt submission timestamp
         */
        public PendingNew(String pendingId, String ownerId, String name,
                          int startId, List<QuestNode> nodes, String versionNote, Instant submittedAt) {
            this.pendingId = pendingId;
            this.ownerId = ownerId;
            this.name = name;
            this.startId = startId;
            this.nodes = nodes;
            this.versionNote = versionNote;
            this.submittedAt = submittedAt;
        }
    }

    /**
     * Stages a new quest for moderation.
     *
     * @param ownerId     owner user id
     * @param name        quest name
     * @param startId     start node id
     * @param nodes       nodes to store
     * @param versionNote version/comment label
     */
    void stageCreate(String ownerId, String name, int startId, List<QuestNode> nodes, String versionNote);

    /**
     * Lists pending "new quest" submissions ordered by submission time descending.
     *
     * @return immutable list of pending new items
     */
    List<PendingNew> listPendingNew();

    /**
     * Approves a pending "new quest" and materializes it as a published quest.
     *
     * @param pendingId moderation id
     * @return generated quest id
     * @throws java.util.NoSuchElementException if the pending item is not found
     */
    String approveCreate(String pendingId);

    /**
     * Rejects a pending "new quest".
     *
     * @param pendingId moderation id
     * @throws java.util.NoSuchElementException if the pending item is not found
     */

    void rejectCreate(String pendingId);

    /**
     * Pending edit submission for moderation of an existing quest.
     */
    @Getter
    final class PendingEdit {
        private final String questId;
        private final String ownerId;
        private final String name;
        private final int startId;
        private final List<QuestNode> nodes;
        private final String versionNote;
        private final Instant submittedAt;

        /**
         * @param questId     target quest id
         * @param ownerId     owner user id
         * @param name        current quest name (for display)
         * @param startId     proposed start node id
         * @param nodes       proposed nodes
         * @param versionNote version/comment label
         * @param submittedAt submission timestamp
         */
        public PendingEdit(String questId, String ownerId, String name,
                           int startId, List<QuestNode> nodes, String versionNote, Instant submittedAt) {
            this.questId = questId;
            this.ownerId = ownerId;
            this.name = name;
            this.startId = startId;
            this.nodes = nodes;
            this.versionNote = versionNote;
            this.submittedAt = submittedAt;
        }
    }

    /**
     * Stages an edit for moderation for an existing quest.
     *
     * @param questId     quest id to edit
     * @param startId     proposed start node id
     * @param nodes       proposed nodes
     * @param versionNote version/comment label
     * @throws java.util.NoSuchElementException if the target quest is not found
     */
    void stageEdit(String questId, int startId, List<QuestNode> nodes, String versionNote);

    /**
     * Lists pending edits ordered by submission time descending.
     *
     * @return immutable list of pending edit items
     */
    List<PendingEdit> listPendingEdits();

    /**
     * Applies a pending edit to the live quest (implementations SHOULD update {@code updatedAt}).
     *
     * @param questId quest id that has a pending edit
     * @throws java.util.NoSuchElementException if the pending edit is not found
     */
    void approveEdit(String questId);

    /**
     * Rejects a pending edit.
     *
     * @param questId quest id that has a pending edit
     * @throws java.util.NoSuchElementException if the pending edit is not found
     */
    void rejectEdit(String questId);
}
